### ISSUE TITLE
SYSTEM/Stabilisation of the whole module

### ISSUE THREAD

**Issue by djoproject** [djoproject/pyshell#100]
### Description
This issue wasn't expected and thus was written after the implementation/modification of a lot of stuff.  But it can be interesting to summarise what was done and what have to be done, to be sure to cover everything.

#### Why this issue occurs ?
So everything started with the upgrade of the loading module (not finished yet, it depends on this issue), the goal was to modernise the parameter saving/loading and to save the minimum amount of information as possible to retrieve the same state after an app restart.
A first problem was the argChecker type that was stored in the parameter itself.  Only the values and the settings properties are saved.  Nevertheless, the type was saved but because of a hack.  It becomes obvious to move the checker in the setting classes and to limit the parameter classes to the data management only.  But a lot of stuff wasn't finished or ready for that.  
 
To be able to create a file/parameter loader stable, the system module must be perfect, fully tested and without any unfinished part.  It wasn't the case.
This issue has been created after the start of these update, the goal here is to keep track of what had been done and what must be done.

#### Why to refactor procedure ?
After the new restriction applied the procedure system, a lot of modifications were done and other were still pending, especially in the procedure file.  The system was able to manage procedure in memory and in file and several call level of procedure was possible.  But now only one level of procedure can be called, if a user want to add more level, it must be done in python.

#### About level and procedure
With the previous version, the system was a multi level model, with the first version of the limited procedure calling, it was a single level model.  But it was wrong, a two level model is needed.  Explanation:
 * main thread
   * first level: can call subscript
     * init script: script to init the software, no suppose to loop, it will be replaced by the shell or the daemon script
     * shell: default cas, an input is available in the console to allow the user to execute a command
     * daemon script: a looping script used when the application run in background, it can execute command.  This part is not implemented yet.
     * command: a command can be started with the init script, the shell or the daemon script but stays at the same level.  A command can be used to execute an action or to start a sub script
  * second level: can not call subscript, no more level available
    * procedure script: can call a list of command.
    * command: the commands executed at this level can only execute action, if a command try to start a sub script from here, an error is raised
 * secondary thread:  a secondary thread can be started from the main thread
   * first level: only purpose of this level, execute a command or start a sub script
     * command: this command has the same power as a command in the main thread, it can execute an action or start a sub script.  Except there is nothing behind the command (no init/daemon script or shell), so when the command is finished, the thread die
   * second level: can not call subscript, no more level available
     * procedure script: same as for the second level in main thread
     * command: same as for the second level in main thread

### Tasks to do
 * [x] create a file for each settings type
 * [x] move checker into settings (env)
 * [x] move manager into its own file
 * [x] move index into settings (cont)
 * [x] redefine level but limited at two level
 * [x] refactor procedure
 * [x] test the new procedure class
 * [x] resolve the remaining TODOs in the code
 * [x] add missing unit test (see coverage result)

### Files to update
 * ./system/*.py
 * ./system/test/*.py

### Dependence for
 * #55
