### ISSUE TITLE
UTILS/Stabilize the package

### ISSUE THREAD

**Issue by djoproject** [djoproject/pyshell#107]
### Description

Several part of the package are not tested or not fully tested, implement the missing tests.
A few small TODOs remains (5 of them at the time of the writing of this issue).  There is no need to create an issue for them (they are really small), just implement/test them at the same time as this issue.

### File to test
 * [ ] exception.py (current cover = 79%)
 * [ ] executing.py (current cover = 95%)
 * [ ] key.py (current cover = 91%)
 * [ ] misc.py (current cover = 56%)
 * [ ] ordereddict.py (current cover = 0%)
 * [ ] parsing.py (current cover = 93%)
 * [x] postprocess.py
 * [ ] printing.py (current cover = 80%)
 * [ ] solving.py (current cover = 97%)
 * [ ] string.py (current cover = 0%)
 * [ ] synchronized.py (current cover = 88%)
 * [x] valuable.py

Because they are simple abstract class, the files in the package utils.abstract do not need to be tested.

### TODO in files
 * executing.py
 * misc.py
 * printing.py
 * solving.py
 * test/misc_test.py

**Comment by djoproject** [comment]
there are two kind of utils files, it should be interesting to split the package:
 * the low level module that are used by everything else in the app
 * the high level module that use a lot of thing coming from everywhere in the app
